from typing import NewType

import strawberry

#: Annotation used for SQLAlchemy `BigInteger` columns.
BigInt = NewType("BigInt", int)

#: Scalar definitions required by the types generated by this library.
#: Register them on your schema with
#: `StrawberryConfig(scalar_map=strawberry_sqlalchemy_scalar_map)`.
strawberry_sqlalchemy_scalar_map = {
    BigInt: strawberry.scalar(
        name="BigInt",
        description="BigInt field",
        serialize=lambda v: int(v),
        parse_value=lambda v: str(v),
    ),
}
